name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up the Flutter SDK
      # Specify a stable channel version for reliability
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Optionally specify a specific Flutter version
          # flutter-version: '3.x' # Replace with desired version, e.g., '3.22.2'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify code formatting (optional, uncomment to enable)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Analyze the project source
      - name: Analyze project source
        run: flutter analyze
